### ISSUE TITLE
Add ShapePopulationViewer extension

### ISSUE THREAD

**Issue by bianchijonas1** [DCBIA-OrthoLab/SlicerCMF#14]
@jcfr @bpaniagua @JEHoctor

Add the following extension: ShapePopulationViewer to the SLICER CMF
*Ps: The extension appears in the Slicer Index (Image bellow), however is not working/installed or available to install.
Thank you
Jonas

![image](https://user-images.githubusercontent.com/47431886/87085488-f46ea500-c1fd-11ea-9136-e20201a67bb5.png)

**Comment by jcfr** [comment]
Thanks for reporting the issue :pray: 

It turns out the ShapePopulationView has been added to SlicerCMF in https://github.com/DCBIA-OrthoLab/SlicerCMF/pull/7 and https://github.com/DCBIA-OrthoLab/SlicerCMF/pull/8

As illustrated on the [ShapePopulationViewer quality dashboard](http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ShapePopulationViewer), errors are reported are specific to macOS and windows. The problem is now tracked in this issue: https://github.com/NIRALUser/ShapePopulationViewer/issues/53

After PR #15  is integrated, the README of this extension will include a link to the source code of all dependent extension along with a link the corresponding quality assurance dashboard.

**Comment by jcfr** [comment]
To follow up, extension now available for download:

![image](https://user-images.githubusercontent.com/219043/87182072-6d7b0480-c2b1-11ea-9773-5b242095f799.png)
